indicators:
  - code: NY.GDP.MKTP.CD
    name: GDP

  - code: SP.POP.TOTL
    name: Population

  - code: SP.DYN.LE00.IN
    name: Life Expectancy

  - code: IT.NET.USER.ZS
    name: Internet Users

  - code: SL.UEM.TOTL.ZS
    name: Unemployment