COUNTRY_ANALYTICS = """
SELECT *
FROM MART_COUNTRY_ANALYTICS
"""

COUNTRY_LIST = """
SELECT DISTINCT country_name
FROM DIM_COUNTRY
ORDER BY country_name
"""

COUNTRY_METRICS = """
SELECT *
FROM MART_COUNTRY_ANALYTICS
WHERE country_name = '{}'
ORDER BY year
"""